### ISSUE TITLE
whitelist 

### ISSUE THREAD

**Issue by genrihx2** [Be1zebub/Stop-Discord-Nitro-Scam-BOT#5]
баги есть
нужно добавить whitelist cdn.discordapp.com

**Comment by Be1zebub** [comment]
![image](https://user-images.githubusercontent.com/34854689/154652024-0be8d38a-a677-47dc-a816-c128d9030707.png)
works fine now, I fixed this bug yesterday

**Comment by genrihx2** [comment]
Спасибо
